XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXX X XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX
        XXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXX
            XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX
        X
        XXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXX
            XXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
        X
        XXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXX
        X
        XXXXXXXXXXXXXXXX XXXXX X
            XXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXX XXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXX
        X
        XXXXXXXXXXXXXXXX XXXXXX X
            XXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXXXXXXX
        X
        XXXXXXXXXXXXXXXX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X
        XXXXXXXXXXXXXX X
            XXXXXX XXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXXXXX
    BB BBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            BBB BBBBBBB BB BBBBBBBB
                XXXXXXX
            BBBBBB
        XXXXXX
    BBBBB
    XXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
XXXXXX

XXXXXXX
XXXXXXX
