XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXXXX X XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX
        XXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXX
            XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXX
        X
        XXXXXXX XX X
            XXXXXX XXXXXXXX
        X
        XXXXXXXXXXX X
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXX XXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
        X
        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X
        XXXXXXXX XXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
        X
        XXXXXXX XXXXXX XXXXXXXXXXXXX XXXXX X
            XXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXX
        X
        XXXXXXX XXX XXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXX XXXXX
        X
        XXXXXXX XXX XXXXXXXXXXXXX XX X
            XXXXXXXX XXXXX
            XXXXXXXXXXX XXX XXXXX XXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX
        XXXXXXX
            XXXXXXX
                XXXX
                    XXXXXXXXXXXXXX
                    XXXXXXXX XXXXXXXXX
                    XXXXXXXXXXXXXXX
                XXXXX
            XXXXXXXX
            XXXXXXX
                BBB BBBBB BB BBBBBB
                    XXXX
                        XXXXXXXXX
                        XXXXXXXXX
                        XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBXXXXXXXX XXXXXXXXXXXXXX
                    XXXXX
                BBBBB
                    XXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                BBBBBB
            XXXXXXXX
        XXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
            XXXXXXX
                XXXX
                    XXXXXXXXXXXXXXX XXXXXXX
                    XXXXXXXXX XXXXXXXXXX
                    XXXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXX
                XXXXX
            XXXXXXXX
            XXXXXXX
                BBB BBBBBBBBBBB BB BBBBBBBBBBBB
                    XXXX
                        XXXXXXXXX
                        XXXXXXXXX
                        XXXXXXXXX
                        XXXXXXXXX
                    XXXXX
                BBBBB
                    XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                BBBBBB
            XXXXXXXX
        XXXXXXXX
    XXXXXX
XXXXXX

XXXXXXX
XXXXXXX
