BBBB BBBBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXX XX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX
  XXXXXXX gettext(u'Cinema Ticket Reservation') XXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBXX
XXXXXXX
XXXXXX
XXXXXXXX
  XXXX gettext(u'Cinema Ticket Reservation') XXXXX
  XXXX XXXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBXX gettext(u'Home') XXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Streaming') XXXX
    BB BBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
        BBBB
          XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
        BBBBB
        XXXXXX gettext(u'Welcome, %(user.username)s') SSSSSSSS SSSSSSSSSSSSSSSSSXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Profile') XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBXX gettext(u'Logout') XXXX
      XXXXXX
    BBBB
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Login') XXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBXX gettext(u'Sign Up') XXXX
    BBBBB
  XXXXXX
XXXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXX XXXXXXXXBBB BBBBBBXX
    XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX gettext(u'Search movies...') X XXXXXXXFFFFFFFFFFXX
    XXXXXXX XXXXXXXXXXXXXX gettext(u'Search') XXXXXXXXX
  XXXXXXX
XXXXXX

BB BBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    BBB BBBBB BB BBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBB
          XXXX XXXXXX XXXXXXX
        BBBB
          XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
        BBBBB
      XXXXXX
    BBBBBB
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXX
BBBBB

XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Book a Movie Ticket') XXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    BBB BBBBB BB BBBBBB
      BB BBB BBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBB
            XXXX XXXXXX XXXXXXX
          BBBB
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
          BBBBB
          XXXX XXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXX XXXXXXXXXXXXXX
              BBB B BB BBBBBBB
                BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBB
                  XX XXXXXXXXXX XXXXXXXXXXXXX
                BBBB
                  XX XXXXXXXXXX XXXXXXXXXXXXX
                BBBBB
              BBBBBB
            XXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBXX gettext(u'Book Now') XXXX
          XXXXXX
        XXXXXX
      BBBBB
    BBBBBB
  XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Watch Online (Streaming)') XXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    BBB BBBBB BB BBBBBB
      BB BBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBB
            XXXX XXXXXX XXXXXXX
          BBBB
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
          BBBBB
          XXXX XXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXX XXXXXXXXXXXXXX
              BBB B BB BBBBBBB
                BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBB
                  XX XXXXXXXXXX XXXXXXXXXXXXX
                BBBB
                  XX XXXXXXXXXX XXXXXXXXXXXXX
                BBBBB
              BBBBBB
            XXXXXX
            BB BBBBBBBBBBBBBBBBBBBBB
              XX XXXXXXXXXXXXXXXX XXXXXXXX gettext(u'Stream') XXXX
            BBBB
              XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Login to Stream') XXXX
            BBBBB
          XXXXXX
        XXXXXX
      BBBBB
    BBBBBB
  XXXXXX
XXXXXXXXXX

XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX
XXXXXXX
