BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXX gettext(u'Seat Selection') XXXXXXXX
    XXXXXXX
        XX XXXX XXXXXXXX XXXXXX XXXXXX XXXXXXXXX XX
        XXXX X
            XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXX XXXXXX
            XXXXXX XXXXX
            XXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXXX XX X
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXXX XXXXX X
            XXXXXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXX XXX XX
        X

        XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXX X
            XXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXX XXXX XX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXX XXXXX XXXXX
        X

        XXXXXXXXXXXXXXX XXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXXX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXX
        X

        XXXXX X
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXX XXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXX
        X

        XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXX XXXXXXXXXXXX
        X

        XX XXXXX XXXXXX XX
        XXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXX XXXXXX
            XXXX XX
            XXXXX XX
            XXXXXX XX
            XXXXXXX XX
            XXXXXXXXXXX XXXXXXX XX XX XXXXX
            XXXXXX XXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXX
        X

        XXXXXX XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
        X

        XXXXXX XXXXXX X
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXX XXXXX
        X

        XXXXXX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXX XXXXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX gettext(u'Seat Selection for %(title)s') SSSS SSSSSSSSS SSS SSSSSSSSSXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXX XXXXXXXXXXX gettext(u'Your Name:') XXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX
            
            XXXXXX XXXXXXXXXXXX gettext(u'Your Email:') XXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
            
            XXXXXX XXXXXXXXXXXXXX gettext(u'Select Seat:') XXXXXXXX
            XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
                BBB BBBB BB BBBBB
                    XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBXXXXXXXXBBBBBX
                         gettext(u'\n                            Seat %(seatnum)s\n                        ') 
                            SSSS SSSSSSSSSSS
                        
                        BB BBBBBBBBBBBBBBX  gettext(u'Booked') BBBBB
                    XXXXXXXXX
                BBBBBB
            XXXXXXXXX

XXXX XXX XXXXXXX XXXXXX XXXXX XXX
            XXXXXX XXXXXXXXXXXXX gettext(u'Payment Amount (ETB):') XXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Enter payment amount') X XXXXXXXXX

            XXXXXXX XXXXXXXXXXXXXX gettext(u'Confirm Reservation & Pay') XXXXXXXXX
        XXXXXXX

        BB BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBB
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        BBB BBBB BB BBBBB
            XXXX XXXXXXXXXXX BB BBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFFXXX
                BB BBB BBBBBBBBBBBBBB
                     gettext(u'Seat %(seatnum)s') SSSS SSSSSSSSSSS
                BBBB
                    XXXXXX gettext(u'Booked') XXXXXXX
                BBBBB
            XXXXXX
        BBBBBB
    XXXXXX

    XXXX XXXXX XXX XXXXXX XXXX XXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX gettext(u'Sorry, this seat is already booked. Please select another available seat.') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX X
            XX XXXXXXXXXX X
                XXXXXXXXXXXX
            X XXXX X
                XX XXXXXX XXX XXXXXX XXXXXXXX XXXX XXXXXXX XXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
            X
        X

        XXXXXXXX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        X

        XXXXXXXX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        X
    XXXXXXXXX
XXXXXXX
XXXXXXX