XXXXXXXXX XXXXX
XXXXX XXXXXXBBBBBBBBBBBBBBBBBBBBXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXX gettext(u'Ticket Confirmation') XXXXXXXX
    XXXXXXX
        XXXX X
            XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXX X
            XXXXXXXXXXX XXXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXX XXXXXX
            XXXXXX XXXXX
        X

        XXXXXXX XX X
            XXXXXX XXXXXXXX
        X

        XXXXXXX X X
            XXXXXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXX XXX XX
        X

        XXXXXXX X
            XXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
        X

        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX gettext(u'Your Booking is Confirmed!') XXXXX

    XXXX XXXXXXXXXXXXXXX
        XXXXXXXXX
        XXXXXXXXXXX gettext(u'Name:') XXXXXXXXX XXXX
        XXXXXXXXXXX gettext(u'Email:') XXXXXXXXX XXXX
        XXXXXXXXXXX gettext(u'Seat:') XXXXXXXXX XXXX
        XXXXXXXXXXX gettext(u'Show Time:') XXXXXXXXX XXXX

        XXXX XX XXXX XXXX XX XXXXXXXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Download QR Code') XXXX
    XXXXXX

    XXXX XXXX XXXXXXXXX XXXX XXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX
        XX XXXXX XX XXXX XXXX XXXXXXXXXXX
        XXXXX XXXXXX X XXXXXXXXXXX XXX 
XXXXXX 
XXXXX 
XXXXX 
XXXXXX X

        XX XXXXXXXX XX XXXX
        XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XX X XXX XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXX
            XXXXXX XXXX
            XXXXXXX XXX
        XXX

        XX XXXX X XXXX XXXX XXXXX XXXXXXXX
        XXXXXXXXXXXXX XX X
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXX X
                XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XX XXXXX
    XXXXXXXXX
XXXXXXX
XXXXXXX