# Generated by Django 4.2.20 on 2025-04-20 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('show_time', models.DateTimeField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('is_booked', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('reservation_time', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.movie')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.seat')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.movie')),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.seat')),
            ],
        ),
    ]
