# Generated by Django 4.2.20 on 2025-04-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
