# Generated by Django 4.2.20 on 2025-04-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='num_rows',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='movie',
            name='seats_per_row',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
