# Generated by Django 4.2.20 on 2025-04-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_movie_num_rows_movie_seats_per_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_streaming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='stream_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
