# Generated by Django 4.2.20 on 2025-04-21 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_movie_is_streaming_movie_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='reservations.movie')),
            ],
        ),
    ]
