# Generated by Django 4.2.20 on 2025-04-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_movie_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default='default_poster.jpg', null=True, upload_to='movie_posters/'),
        ),
    ]
