# Generated by Django 5.2.4 on 2025-07-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_video_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_file',
            field=models.FileField(blank=True, null=True, upload_to='trailers/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
