# Generated by Django 5.2.4 on 2025-08-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_reservation_is_paid_transaction_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
