# Generated by Django 5.2.4 on 2025-08-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_reservation_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_streaming',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='stream_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='trailer',
        ),
    ]
