# Generated by Django 5.2.4 on 2025-08-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_remove_movie_is_streaming_remove_movie_stream_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=8, verbose_name='Ticket Price (ETB)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='num_rows',
            field=models.PositiveIntegerField(default=5, verbose_name='Number of Rows'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='seats_per_row',
            field=models.PositiveIntegerField(default=10, verbose_name='Seats per Row'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='show_time',
            field=models.DateTimeField(verbose_name='Show Time'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_file',
            field=models.FileField(blank=True, null=True, upload_to='trailers/', verbose_name='Trailer File'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='Trailer URL'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='reservations.movie', verbose_name='Movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Email Sent'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is Paid'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.movie', verbose_name='Movie'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Reservation Time'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.seat', verbose_name='Seat'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.CharField(max_length=100, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Is Booked'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.movie', verbose_name='Movie'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=5, verbose_name='Seat Number'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation', verbose_name='Reservation'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=100, verbose_name='Transaction ID'),
        ),
    ]
