# Generated by Django 5.2.4 on 2025-08-29 17:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_remove_movie_rating_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Trailer'),
        ),
    ]
