# Generated by Django 5.2.4 on 2025-08-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_alter_movie_poster_alter_movie_trailer_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_file',
            field=models.FileField(blank=True, null=True, upload_to='trailers/', verbose_name='Trailer File'),
        ),
    ]
