# Generated by Django 5.2.4 on 2025-09-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_alter_movie_poster_alter_movie_trailer_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer_file',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='trailer_url',
        ),
    ]
