# Generated by Django 5.2.4 on 2025-08-11 10:37

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Streaming Analytics',
                'verbose_name_plural': 'Streaming Analytics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StreamingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('documentary', 'Documentary'), ('short', 'Short Film'), ('other', 'Other')], default='movie', max_length=20)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('video_file', models.FileField(blank=True, help_text='Upload video securely', null=True, upload_to='secure_videos/')),
                ('video_url', models.URLField(blank=True, help_text='Optional external video URL', null=True)),
                ('price_per_view', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Total duration in minutes')),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_plays', models.PositiveIntegerField(default=0)),
                ('unique_viewers', models.PositiveIntegerField(default=0)),
                ('total_watch_time_minutes', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='StreamingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subscription_type', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=10)),
                ('chapa_tx_ref', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_ref', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StreamViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('watch_time_minutes', models.PositiveIntegerField(default=0)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.streamingcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content')},
            },
        ),
    ]
