# Generated by Django 5.2.4 on 2025-07-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video_url', models.FileField(blank=True, null=True, upload_to='streaming_videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('trailer', models.FileField(blank=True, null=True, upload_to='streaming_trailers/')),
            ],
        ),
        migrations.RenameField(
            model_name='video',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='youtube_url',
            new_name='trailer_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='video',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='videos/default.mp4', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
