# Generated by Django 5.2.4 on 2025-08-30 17:57

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import streaming.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='profile_pics/default_profile.png', upload_to=streaming.models.profile_image_path, verbose_name='Profile Picture')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('history_cleared_at', models.DateTimeField(blank=True, null=True, verbose_name='History Cleared At')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=255, verbose_name='Video Title')),
                ('watch_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Watch Date')),
                ('duration_watched', models.PositiveIntegerField(default=0, verbose_name='Duration Watched (minutes)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StreamingAnalytics',
        ),
        migrations.CreateModel(
            name='StreamingAnalyticsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Streaming Analytics',
                'verbose_name_plural': 'Streaming Analytics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('streaming.streamingcontent',),
        ),
        migrations.RemoveField(
            model_name='streamingcontent',
            name='total_watch_time_minutes',
        ),
        migrations.RemoveField(
            model_name='streamviewlog',
            name='watch_time_minutes',
        ),
        migrations.AddField(
            model_name='streamingcontent',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='Average Rating'),
        ),
        migrations.AddField(
            model_name='streamingcontent',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('drama', 'Drama'), ('comedy', 'Comedy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('sci-fi', 'Sci-Fi'), ('horror', 'Horror'), ('fantasy', 'Fantasy'), ('animation', 'Animation'), ('adventure', 'Adventure'), ('crime', 'Crime'), ('mystery', 'Mystery'), ('family', 'Family'), ('history', 'History'), ('music', 'Music'), ('war', 'War'), ('western', 'Western'), ('biography', 'Biography'), ('sport', 'Sport'), ('other', 'Other')], default='other', max_length=30, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='streamingcontent',
            name='hls_folder',
            field=models.CharField(blank=True, help_text='Path to generated HLS folder', max_length=255, null=True, verbose_name='HLS Folder'),
        ),
        migrations.AddField(
            model_name='streamingcontent',
            name='language',
            field=models.CharField(choices=[('am', 'Amharic'), ('en', 'English'), ('om', 'Afaan Oromo'), ('ti', 'Tigrinya'), ('so', 'Somali'), ('ar', 'Arabic'), ('fr', 'French'), ('es', 'Spanish'), ('hi', 'Hindi'), ('other', 'Other')], default='en', max_length=20, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='streamingcontent',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Ratings'),
        ),
        migrations.AddField(
            model_name='streamingcontent',
            name='total_watch_time_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Watch Time (seconds)'),
        ),
        migrations.AddField(
            model_name='streamingsubscription',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='streamviewlog',
            name='watch_time_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Watch Time (seconds)'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='category',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('documentary', 'Documentary'), ('short', 'Short Film'), ('other', 'Other')], default='movie', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='completion_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Completion Rate'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Total duration in minutes', verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='price_per_view',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Price per View'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='release_date',
            field=models.DateField(verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='total_plays',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Plays'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='unique_viewers',
            field=models.PositiveIntegerField(default=0, verbose_name='Unique Viewers'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video securely', null=True, upload_to='secure_videos/', validators=[streaming.models.validate_video_extension], verbose_name='Upload Video'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional external video URL', null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='streamingsubscription',
            name='access_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Access Expires At'),
        ),
        migrations.AlterField(
            model_name='streamingsubscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='streamingsubscription',
            name='chapa_tx_ref',
            field=models.CharField(max_length=100, unique=True, verbose_name='Chapa Transaction Reference'),
        ),
        migrations.AlterField(
            model_name='streamingsubscription',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='streamingsubscription',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='streamingsubscription',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='streamingsubscription',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='streamingsubscription',
            name='subscription_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=10, verbose_name='Subscription Type'),
        ),
        migrations.AlterField(
            model_name='streamviewlog',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='streamviewlog',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Viewed'),
        ),
        migrations.AlterField(
            model_name='streamviewlog',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_ref',
            field=models.CharField(max_length=100, unique=True, verbose_name='Transaction Reference'),
        ),
        migrations.AddField(
            model_name='streamingrating',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='streaming.streamingcontent'),
        ),
        migrations.AddField(
            model_name='streamingrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='streamingrating',
            unique_together={('user', 'content')},
        ),
    ]
