# Generated by Django 5.2.4 on 2025-08-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingcontent',
            name='hls_folder',
            field=models.CharField(blank=True, help_text='Path to generated HLS folder', max_length=255, null=True),
        ),
    ]
