# Generated by Django 5.2.4 on 2025-08-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_streamingcontent_hls_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamingcontent',
            name='duration_minutes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='hls_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='secure_videos/'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
