# Generated by Django 5.2.4 on 2025-08-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_alter_streamingcontent_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamingcontent',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Total duration in minutes'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='hls_folder',
            field=models.CharField(blank=True, help_text='Path to generated HLS folder', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video securely', null=True, upload_to='secure_videos/'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional external video URL', null=True),
        ),
    ]
