# Generated by Django 5.2.4 on 2025-08-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0006_alter_streamingcontent_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamingcontent',
            old_name='total_watch_time_minutes',
            new_name='total_watch_time_seconds',
        ),
        migrations.RenameField(
            model_name='streamviewlog',
            old_name='watch_time_minutes',
            new_name='watch_time_seconds',
        ),
    ]
