# Generated by Django 5.2.4 on 2025-08-20 19:47

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import streaming.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0007_rename_total_watch_time_minutes_streamingcontent_total_watch_time_seconds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingcontent',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='streamingcontent',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='category',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('documentary', 'Documentary'), ('short', 'Short Film'), ('other', 'Other')], default='movie', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='completion_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Completion Rate'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Total duration in minutes', verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='hls_folder',
            field=models.CharField(blank=True, help_text='Path to generated HLS folder', max_length=255, null=True, verbose_name='HLS Folder'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='price_per_view',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Price per View'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='release_date',
            field=models.DateField(verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='total_plays',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Plays'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='total_watch_time_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Watch Time (seconds)'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='unique_viewers',
            field=models.PositiveIntegerField(default=0, verbose_name='Unique Viewers'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video securely', null=True, upload_to='secure_videos/', verbose_name='Upload Video'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional external video URL', null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='streamingsubscription',
            name='access_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Access Expires At'),
        ),
        migrations.AlterField(
            model_name='streamingsubscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='streamingsubscription',
            name='chapa_tx_ref',
            field=models.CharField(max_length=100, unique=True, verbose_name='Chapa Transaction Reference'),
        ),
        migrations.AlterField(
            model_name='streamingsubscription',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='streamingsubscription',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='streamingsubscription',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='streamingsubscription',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='streamingsubscription',
            name='subscription_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=10, verbose_name='Subscription Type'),
        ),
        migrations.AlterField(
            model_name='streamviewlog',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='streamviewlog',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Viewed'),
        ),
        migrations.AlterField(
            model_name='streamviewlog',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='streamviewlog',
            name='watch_time_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Watch Time (seconds)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_ref',
            field=models.CharField(max_length=100, unique=True, verbose_name='Transaction Reference'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default_profile.png', upload_to=streaming.models.profile_image_path, verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='duration_watched',
            field=models.PositiveIntegerField(default=0, verbose_name='Duration Watched (minutes)'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='video_title',
            field=models.CharField(max_length=255, verbose_name='Video Title'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='watch_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Watch Date'),
        ),
        migrations.CreateModel(
            name='StreamingRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='streaming.streamingcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content')},
            },
        ),
    ]
