# Generated by Django 5.2.4 on 2025-08-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0008_streamingcontent_avg_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamingcontent',
            name='avg_rating',
        ),
        migrations.AddField(
            model_name='streamingcontent',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='Average Rating'),
        ),
        migrations.AlterField(
            model_name='streamingcontent',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Ratings'),
        ),
    ]
