# Generated by Django 5.2.4 on 2025-08-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0009_remove_streamingcontent_avg_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingcontent',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('drama', 'Drama'), ('comedy', 'Comedy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('sci-fi', 'Sci-Fi'), ('horror', 'Horror'), ('fantasy', 'Fantasy'), ('animation', 'Animation'), ('adventure', 'Adventure'), ('crime', 'Crime'), ('mystery', 'Mystery'), ('family', 'Family'), ('history', 'History'), ('music', 'Music'), ('war', 'War'), ('western', 'Western'), ('biography', 'Biography'), ('sport', 'Sport'), ('other', 'Other')], default='other', max_length=30, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='streamingcontent',
            name='language',
            field=models.CharField(choices=[('am', 'Amharic'), ('en', 'English'), ('om', 'Afaan Oromo'), ('ti', 'Tigrinya'), ('so', 'Somali'), ('ar', 'Arabic'), ('fr', 'French'), ('es', 'Spanish'), ('hi', 'Hindi'), ('other', 'Other')], default='en', max_length=20, verbose_name='Language'),
        ),
    ]
