# Generated by Django 5.2.4 on 2025-08-24 09:35

import streaming.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0010_streamingcontent_genre_streamingcontent_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamingcontent',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video securely', null=True, upload_to='secure_videos/', validators=[streaming.validators.validate_video_extension], verbose_name='Upload Video'),
        ),
    ]
