# Generated by Django 5.2.4 on 2025-08-24 10:00

import streaming.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0011_alter_streamingcontent_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamingcontent',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video securely', null=True, upload_to='secure_videos/', validators=[streaming.models.validate_video_extension], verbose_name='Upload Video'),
        ),
    ]
