# Generated by Django 5.2.4 on 2025-08-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0012_alter_streamingcontent_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='history_cleared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='History Cleared At'),
        ),
    ]
