# Generated by Django 5.2.4 on 2025-08-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0013_userprofile_history_cleared_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StreamingAnalytics',
        ),
    ]
