# Generated by Django 5.2.4 on 2025-08-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0014_delete_streaminganalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingAnalyticsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Streaming Analytics',
                'verbose_name_plural': 'Streaming Analytics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('streaming.streamingcontent',),
        ),
    ]
