# Generated by Django 5.2.4 on 2025-08-27 08:57

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0016_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingsubscription',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
