# Generated by Django 5.2.4 on 2025-08-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0017_streamingsubscription_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamingsubscription',
            name='country',
        ),
    ]
