# Generated by Django 5.2.4 on 2025-08-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0018_remove_streamingsubscription_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamviewlog',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
    ]
