BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX

    XXXX XXXXXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXX XXXXX gettext(u'Profile Picture') X XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBBBBBBB
                
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Update Picture') XXXXXXXXX
            XXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX gettext(u'Stats') XXXXX
        XXXXXXXXXXX gettext(u'Total Videos Watched:') XXXXXXXXX XXXX
        XXXXXXXXXXX gettext(u'Total Watch Time:') XXXXXXXXX   gettext(u'minutes') XXXX
    XXXXXX

    XXXX XXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX gettext(u'Watch History') XXXXX
        BB BBBBBBBBBBBBB
            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXXX
                    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Video Title') XXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Watch Date') XXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Duration Watched') XXXXX
                    XXXXX
                XXXXXXXX
                XXXXXXX
                    BBB BBBBBBB BB BBBBBBBBBBBBB
                    XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXFFFFFFF FF F FFFFXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXX  gettext(u'min') XXXXX
                    XXXXX
                    BBBBBB
                XXXXXXXX
            XXXXXXXX
        BBBB
            XXX gettext(u'No watch history found.') XXXX
        BBBBB
    XXXXXX

XXXXXX
BBBBBBBB