BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXXXXX
  XXXXXXXXXXXXXXX XX X
    XXXXXXXXXXX XXXXX
    XXXXXXXX XX
    XXXXXXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXXXXX XX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXX XXXXXX
    XXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXX XXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
  X

  XXXXXXXXXXXXXXX XXX X
    XXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXX XX X
    XXXXXXX XXXX X XXX XX
    XXXXXXXXXXXX XXXXX
    XXXXXX XXXXX
  X

  XXXXXXXXXXXXXXX X X
    XXXXXXX XXX XX
    XXXXXX XXXXX
    XXXXXXXXXX XXXXXXX
  X

  XXXXXXXXXX X
    XXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXX XXX XXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX
  X
XXXXXXXX

XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'Streaming Content') XXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXX
  BB BBBBBBBB
    XXXX
      BBB BBBBBBB BB BBBBBBBB
        XXXX
          BB BBBBBBBBBBBBBBBBB
            XXXX XXXXXX XXXXXX XX
          BBBB
            XXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
          BBBBB

          XXXXXXXXX
          XXX gettext(u'Category: %(content.get_category_display)s') SSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSXXXX
          XXX gettext(u'Release Date: %(content.release_date)s') SSSSSSS SSSSS SSSSSSSSSSSSSSSSSSSSSSSSXXXX
          XXX gettext(u'Duration: %(content.duration_minutes)s minutes') SSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSXXXX

          BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXX gettext(u'Watch Now') XXXX
          BBBB
            XXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'No video available') XXXXXXX
          BBBBB
        XXXXX
      BBBBBB
    XXXXX
  BBBB
    XX XXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXX gettext(u'No streaming content available yet.') XXXX
  BBBBB
XXXXXX
BBBBBBBB
