BBBB BBBB
XXXXXXXXX XXXXX
XXXXXX
XXXXXX
    XXXXXXX gettext(u'User Login') XXXXXXXX
XXXXXXX
XXXXXX
    XXXX gettext(u'Login') XXXXX

    BB BBBBBBBB
        BBB BBBBBBB BB BBBBBBBB
            XX XXXXXXXXXXXXXXXXXXXXXX
        BBBBBB
    BBBBB

    XXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXX XXXXXX XXXXX XX XXXXX XXXXXX XXXXXXXX XXXX XXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX

        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Username') X XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Password') X XXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXX gettext(u'Login') XXXXXXXXX
    XXXXXXX

    XXX gettext(u"Don't have an account?")  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBXX gettext(u'Sign up') XXXXXXXX
XXXXXXX
XXXXXXX