BBBB BBBBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXX XX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX
  XXXXXXX gettext(u'Sign Up - Streaming Subscription') XXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBXX
XXXXXXX
XXXXXX
  XXXX gettext(u'Sign Up for Streaming Subscription') XXXXX

  XXXXX XXXXXXBBB BBBBBBXXX  gettext(u'Back to Home') XXXXXXXX

  BB BBBBBBBB
    XXX XXXXXXXXXXXXXXXXX
      BBB BBBBBBB BB BBBBBBBB
        XXX BB BBBBBBBBBBBB XXXXXXXX BBBBBXXXXXX
      BBBBBB
    XXXXX
  BBBBB

  XXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB

    

    XXXXX
      XXXX
      
      
    XXXXXX

    XXXXX
      XXXX
      
      
    XXXXXX

    XXXXX
      XXXX
      
      
    XXXXXX

    XXXXX
      XXXX
      
      
    XXXXXX

    XXXXX
      XXXXXX XXXXXXXXXXXXXX gettext(u'Subscription Plan') XXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXX gettext(u'Monthly - 500 ETB') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXX gettext(u'Annual - 5000 ETB') XXXXXXXXX
      XXXXXXXXX
      
    XXXXXX

    XXXXXXX XXXXXXXXXXXXXX gettext(u'Sign Up') XXXXXXXXX
  XXXXXXX
XXXXXXX
XXXXXXX