BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB
XXXXXXXXX
XXX gettext(u'Category:')  XXXX
XXX gettext(u'Duration:')    gettext(u'minutes') XXXX

BB BBBBBBBBB
  XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    BB BBB BBBBBB
      XXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
    BBBBB
     gettext(u'Your browser does not support the video tag.') 
  XXXXXXXX

  BB BBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  BBBBB

  XXXXXXXX
XXXXXXXXXXX X
  XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXX X XXX
  XXXXX XXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXX
  XXXXX XXXXXXXXX X XXX

  BB BBBBBB
  XX XXXXXXXXXXXXXXXXXXX X
    XXXXX XXX X XXX XXXXX XXXXXXXXXXXXX XXXX XXX
    XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX
  X XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXX X XXXXXXXXX
  X
  BBBBB

  XXX XXXXXXXXX X XXXXXX
  XXX XXXXXXXX X XX
  XXX XXXXXXXXXXXXXXXXXX X XX
  XXX XXXXXXXXXXX X XXXXXX

  XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXX X X
      XXXXXX XXXXXX
      XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XX
    XXXXX XXXXXXX X X
      XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXX XXXXXXXXX
    XX
    XX XXXXXX XX XXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX
    X
    XXXXXXXXXXXXXXXX X XXXXXXX XXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XX
      XXXXXXXXXXXXXXX
  X

  XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
    XX XXXXXXXXXXXXXXXXXXX X X XX XXXXXXXXXXXXXXXXX X XX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX
      XXXXXXXXXXXXXXXXXX X XX
    X
  X

  XXXXXXXX XXXXXXXXXXXXXXXXXXX X
    XX XXXXXXXXXXXXXX X
      XXXXXXXXXXX X XXXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX
    X
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X XXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXX XXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X XXXXXXXXX X XXXXXX XXXXXXXX XXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    XX XXXXXXXXXXXX XXXXXXX
    XXXXX XXX X XXXXXXXXXXXXXXXXXX
    XXXXX XXXXX X XXX X XXXXXXXXX
    XX XXXXXX X X XX XXXXX X XX XXXXXXXXXXXXXXXXXX XX XXXXXX
    XXXXXXXX X XXXX
  XXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X XXXXXXXXX X XXXXXX XXXXXXXXXXX XXXXXXXXX XXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X XXXXXXXXXXXXXXXXXXX XXXXXXXX XXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXX
  XXXXXXXXXXXXXX XX XXXXXXXX XXXXXXX
XXXXX
XXXXXXXXX

BBBB
  XXX gettext(u'No video available.') XXXX
BBBBB
BBBBBBBB