BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Streaming Analytics') BBBBBBBB

BBBBB BBBBBBBBBB
XXXXXXX
    XXXX X XXXXXXXXXXX XXXXXXXX X
    XXXXXXXXXXXXXXXXXXXX X XXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXX X
    XX X XXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXX XXXXX X
    XXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX XXXXX X
    XXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXX X XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX X
    XXXXX X XXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXX X
    XXXXX XXX XXXXX XX X XXXXXXXX XXXX XXXXX XXXXXXX XXX XXXXX XXXXXXXX XXXXXXXXXXX XXXXX X
    XXXXX XX X XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX X
    XXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXX X
    XXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXX XXXX XXXXX XXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXX X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX  gettext(u'Streaming Analytics') XXXXX

    XXXX XXXXXXXXXXXXXXXX
        XXXXX gettext(u'Total Views: %(total_views)s') SSSSS SSSSSS SSSSSSSSSSSSSSSXXXXXX
        XXXXX gettext(u'Unique Viewers: %(total_unique_viewers)s') SSSSSS SSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSXXXXXX
        XXXXX gettext(u'Total Watch Time: %(total_watch_time_minutes)s mins') SSSSS SSSSS SSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX gettext(u'Views by Country:') XXXXXXXXX
        BB BBBBBBBBBBBBB
            XXXX
                BBB BBBBBBB BB BBBBBBBBBBBBB
                    XXXX gettext(u'%(country.country__name|default:"Unknown")s - %(country.total_views|default:0)s views (%(country.unique_viewers|default:0)s unique)') SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS S SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSXXXXX
                BBBBBB
            XXXXX
        BBBB
            XXX gettext(u'No country data available.') XXXX
        BBBBB
    XXXXXX

    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX gettext(u'⬇️ Download CSV') XXXX

    XXXXXXX
        XXXXXXX
            XXXX
                XXXX gettext(u'Content') XXXXX
                XXXX gettext(u'Total Views') XXXXX
                XXXX gettext(u'Unique Viewers') XXXXX
                XXXX gettext(u'Total Watch Time (mins)') XXXXX
                XXXX gettext(u'Completion Rate (%%)') XXXXX
            XXXXX
        XXXXXXXX
        XXXXXXX
            BBB BBBB BB BBBBBBBBBBBBB
            XXXX
                XXXXXXXXX
                XXXXFFFFFFFFFXXXXX
                XXXXFFFFFFFFFXXXXX
                XXXXFFFFFFFFFFFFFFFFFFFFFFFXXXXX
                XXXXFFFFFFFFFXXXXX
            XXXXX
            BBBBB
            XXXX
                XXX XXXXXXXXXXXX gettext(u'No analytics available yet.') XXXXX
            XXXXX
            BBBBBB
        XXXXXXXX
    XXXXXXXX
XXXXXX
BBBBBBBB